<a href="https://colab.research.google.com/github/egipot/Udemy_Python_DataAnalysisAndVisualization_course/blob/main/1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

In [5]:
#pass a list into an array
my_array1 = np.array(my_list1)

In [6]:
my_array1

array([1, 2, 3, 4])

In [8]:
my_list2 = [11,22,33,44]

In [10]:
#combine
my_lists = [my_list1, my_list2]

In [11]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array2 = np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
my_array2.shape

(2, 4)

In [15]:
#find the data type
my_array2.dtype

dtype('int64')

In [17]:
#create an array with 5 zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
#another way to define an array with 5 zeros, directly assigning to a variable
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array

array([0., 0., 0., 0., 0.])

In [20]:
my_zeros_array.dtype

dtype('float64')

In [21]:
#create an array of ones
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#create an empty array
np.empty(5)

array([0., 0., 0., 0., 0.])

In [24]:
#create an identity matrix or identity array that is a diagonal of 1 and everything else is 0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#create an identity matrix using np.arange (start, stop, step, dtype=None)
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

8. Using arrays and scalars

In [29]:
5/2

2.5

In [31]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [32]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [34]:
#multiplying arrays (scalar operation)
arr2 = arr1*arr1

In [35]:
arr2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [36]:
#subtracting arrays
arr2-arr1

array([[  0,   2,   6,  12],
       [ 56,  72,  90, 110]])

In [37]:
#dividing arrays
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

9. Indexing Arrays

In [38]:
arr3 = np.arange(0,11)

In [39]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr3[8]

8

In [42]:
arr3[1:5]

array([1, 2, 3, 4])

In [43]:
arr3[0:5]

array([0, 1, 2, 3, 4])

In [44]:
#setting a value with an index range
arr3[0:5] = 100

In [45]:
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
arr4 = np.arange(0,11)

In [47]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr = arr4[0:6]

In [54]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr4

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

^original array (arr4) is affected!

In [57]:
#if you do not want the original array to be affected: use copy
arr_copy = arr4.copy()

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
#indexing arrays [row, column]
arr_2d[1]

array([20, 25, 30])

In [63]:
arr_2d[1,0]

20

In [69]:
arr_2d[2:]

array([[35, 40, 45]])

In [68]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [64]:
#slicing an array [row, column]
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
#slice the bottom row
arr_2d[2]

array([35, 40, 45])

In [74]:
#create an array of zeroes with the size 10x10
arr2d = np.zeros((10,10))

In [75]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
#check the length
arr2d_length = arr2d.shape[1]
arr2d_length

10

In [80]:
#set all elements to 1:
for i in range (arr2d_length):
  arr2d[i] = 1



In [81]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [82]:
#set all elements to index i:
for i in range (arr2d_length):
  arr2d[i] = i

In [83]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [84]:
#fancy indexing - allows us to extract the values in a given row
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [86]:
#can also be in random order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [93]:
#fancy indexing - allows us to extract the values in a given column
arr2d[:,3]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
#set all elements to index i*j (which means rows * column indexes):
for i in range (arr2d_length):
  for j in range (arr2d_length):
    arr2d[i,j] = i*j

In [95]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [96]:
#fancy indexing - allows us to extract the values in a given column
arr2d[:,3]

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [97]:
#fancy indexing - allows us to extract the values in a given row
arr2d[2]

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

10. Array Transposition